import type { Metadata } from "next";
import { Geist, Geist_Mono, Irish_Grover } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const irishGrover = Irish_Grover({
  variable: "--font-irish-grover",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${irishGrover.variable} antialiased bg-[#161618]`}
      >
        {children}
        <p className="text-[#8A8F98] text-center text-sm pb-5">
          Copy @2025 - <span className="font-bold">Myer</span>
        </p>
      </body>
    </html>
  );
}
